apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MiguelSilva04/devship-gitops
    targetRevision: HEAD
    path: apps/demo-app/prod
  revisionHistoryLimit: 5
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
