apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MiguelSilva04/devship-gitops
    targetRevision: HEAD
    revisionHistoryLimit: 10
    path: apps/demo-app/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
    syncPolicy:
     automated:
       selfHeal: true
       prune: true
